version: '3.5'

services:

  nginx:
    image: nginx:1.20.2
    restart: unless-stopped
    depends_on:
      - mlflow
      - minio
    external_links:
      - airflow-webserver
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 5000:5000
      - 19000:9000
      - 19001:9001
      - 8080:8080
    networks:
      - internal

 # do not use "_" in service name or setting: ex. MLFLOW_S3_ENDPOINT_URL in MLflow will fail!
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    expose:
      - "9000"
      - "9001"
    environment:
      - MINIO_ROOT_USER=${S3_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${S3_ROOT_PASSWORD}
    command:
      server --console-address ":9001" /data
    volumes:
      - minio-mlflow:/data
    networks:
      - internal
  
  mlflow:
    build: ./mlflow
    restart: unless-stopped
    depends_on:
      - minio
    external_links:
      - postgres
    expose:
      - "5000"
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=${S3_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${S3_ROOT_PASSWORD}
    entrypoint: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/mlflow
      --default-artifact-root s3://mlflow/
    networks:
      - internal

volumes:
  minio-mlflow: #


networks:
  internal:
    external:
      name: docet_network

